version: '3.7'

services:

  http-client-battle-server:

    image: bb/workout/http-client-battle-server
    network_mode: bridge
    ports:
      - 8080:8080
    build:
      context: .
    environment:
      JAEGER_AGENT_HOST: 'xxx.xxx.xxx.xxx'
      PROMETHEUS_PUSHGATEWAY: 'xxx.xxx.xxx.xxx:9091'
    ulimits:
      nproc: 100000
      nofile:
        soft: 100000
        hard: 200000
